import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navBar";
import { ConnectWalletProvider } from "./context/connectWallet";
import ConnectWalletModal from "@/components/connectWalletModal";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const roboto = localFont({
  src: "./fonts/roboto.ttf",
  variable: "--robot",
  display: "swap",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${roboto.className} font antialiased  `} >
        <ConnectWalletProvider>
          <Navbar />
          <ConnectWalletModal />
          <main className="max-w-7xl mx-auto">

          {children}
          </main>
        </ConnectWalletProvider>
      </body>
    </html>
  );
}
